source "https://rubygems.org"

gem "sinatra"
gem "activerecord"
gem "sinatra-activerecord"
gem "sinatra-flash"
gem "sinatra-redirect-with-flash"
gem "sinatra-contrib"
gem "aescrypt"
gem "delayed_job_active_record"
gem "sidekiq"
gem "redis"
gem "sanitize"

group :development do
 gem "sqlite3"
 gem "tux"
end

group :production do
 gem "pg"
end

group :test do
  gem "rspec"
  gem "rspec-sidekiq"
end
